modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/ZedDevStuff/KeybindsPurger"
license = "MIT"

[[mods]]
modId = "keybindspurger"
version = "${version}"
displayName = "KeybindsPurger"
authors = "ZedDevStuff"
description = '''
Unset all keybinds for a clean slate
'''
displayURL = "https://modrinth.com/mod/keybindspurger"
logoFile = "icon.png"

[[dependencies.keybindspurger]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.keybindspurger]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
