package dev.zeddevstuff.keybindspurger.common;

import java.util.List;

public class Constants
{
	public static final String MOD_ID = "keybindspurger";
	public static final List<String> VANILLA_KEYBINDS = List.of(
		"key.attack",
		"key.use",
		"key.forward",
		"key.left",
		"key.back",
		"key.right",
		"key.jump",
		"key.sneak",
		"key.sprint",
		"key.drop",
		"key.inventory",
		"key.chat",
		"key.playerlist",
		"key.pickItem",
		"key.command",
		"key.socialInteractions",
		"key.screenshot",
		"key.togglePerspective",
		"key.smoothCamera",
		"key.fullscreen",
		"key.spectatorOutlines",
		"key.swapOffhand",
		"key.saveToolbarActivator",
		"key.loadToolbarActivator",
		"key.advancements",
		"key.hotbar.1",
		"key.hotbar.2",
		"key.hotbar.3",
		"key.hotbar.4",
		"key.hotbar.5",
		"key.hotbar.6",
		"key.hotbar.7",
		"key.hotbar.8",
		"key.hotbar.9",
		"key.modmenu.open_menu", // I have no idea why this is here, but I'm gonna assume removing it is bad
		"key.toggleGui",
		"key.toggleSpectatorShaderEffects",
		"key.spectatorHotbar",
		"key.quickActions",
		"key.debug.overlay",
		"key.debug.modifier",
		"key.debug.reloadChunk",
		"key.debug.showHitboxes",
		"key.debug.clearChat",
		"key.debug.crash",
		"key.debug.showChunkBorders",
		"key.debug.showAdvancedTooltips",
		"key.debug.copyRecreateCommand",
		"key.debug.spectate",
		"key.debug.switchGameMode",
		"key.debug.debugOptions",
		"key.debug.focusPause",
		"key.debug.dumpDynamicTextures",
		"key.debug.reloadResourcePacks",
		"key.debug.profiling",
		"key.debug.copyLocation",
		"key.debug.dumpVersion",
		"key.debug.profilingChart",
		"key.debug.fpsCharts",
		"key.debug.networkCharts",
		"key.debug.lightmapTexture"
	);
}
